name: 'Setup Node.js and pnpm with caching'
description: 'Sets up Node.js, pnpm, and configures caching for pnpm store and Turbo'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'
  turbo-cache-prefix:
    description: 'Prefix for Turbo cache key'
    required: false
    default: 'default'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ inputs.node-version }}
        package-manager-cache: false

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      id: pnpm-install
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Cache Turbo
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ inputs.turbo-cache-prefix }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ inputs.turbo-cache-prefix }}-
