= The Genesis of a Comlplicated Contact Me Form
:published_at: 2015-06-30
:hp-tags: Technical, NodeJS, reCaptcha, Firebase, Zapier,

== Connecting Web Services Example

A guide to a overwhelmingly complex application, that is yet so small and simple.

I have simple one pager web resume, hosted via Github Pages. We all know that Github Pages serve static pages only.

But for the fun and the fans (which I apprently don't have any), I wanted to have a contact form too, that would you know send me a message from the page via email. Now that github doesn't allow me to write server side code, and JavaScript cant send an email, I am facing a bit of trouble here ain't I?

Solution: There are two solutions.

Solution 1: Host the resume on a hosting service. Period.

Solution 2: Develop an app that does all this while, leveraging the amazing technologies, and services and in the process learn a thing or two.

Well, as you have guessed I am going withe the second one.


Steps? Please be patient. I am onlu blogging and write the code and configuring things at the same time...

Okay let me cut the crap, and before you walk away, lets get started right away.

== Steps:

=== ...to be continued
