= The Genesis of a Comlplicated Contact Me Form
:published_at: 2015-06-30
:hp-tags: Technical, NodeJS, reCaptcha, Firebase, Zapier

Okay so here's the deal:

I have simple one pager web resume, hosted via Github Pages. If are a fan you should be aware that Github Pages serve static pages only.

But for the fun and the fans (which I apprently don't have any), I wanted to have a contact form too, that would you know send me a message from the page via email. Now that github doesn't allow me to write server side code, and JavaScript cant send an email, I am facing a bit of trouble here ain't I?

== Solutions: 

There are two solutions.

====== Solution 1: 
Host the resume on a hosting service. Go to Sleep. Period.

====== Solution 2: 
Grab a beer. Connect the Github static page to a Firebase NoSQL backend, that pings a Zapier webhook, which delivers a payload to a mandrill service that sends me my damn email. With an additional complexity of adding a Google reCaptcha to the page that can be authenticated from my micro tiny heroku staged app.

Sounds way to complex for a contact me form? Well I warned you!

Having said, that I guess this will get me learning a couple of things, about these amazing tools (PaaS, SaaS, whatever you want to call them). 

Steps? Please be patient. I am only blogging and configuring things at the same time...Okay let me cut the crap, and before you walk away, lets get started right away.

== Steps:

====== 1. Grab a beer:
Just walk to your fridge.

====== 2. Hold your thoughts, for a minute...

=== ...to be continued
