name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * *' # Daily production monitoring
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: raisedadead/portfolio/.github/workflows/lint.yml@main

  test:
    name: Test
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: raisedadead/portfolio/.github/workflows/test.yml@main

  build:
    name: Build
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      CI: true

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-${{
            hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: build-output
          path: dist/
          retention-days: 1

  lighthouse-pr:
    name: Lighthouse (PR Build)
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/lighthouse.yml
    needs: build
    permissions:
      contents: read
      pull-requests: write
    with:
      mode: 'pr-build'
      config-path: '.github/lighthouse/lhci.json'
      compare-baseline: true
    secrets: inherit

  lighthouse-production:
    name: Lighthouse (Production)
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/lighthouse.yml
    with:
      mode: 'production'
      config-path: '.github/lighthouse/lhci.json'
      urls: |
        https://mrugesh.dev
        https://mrugesh.dev/blog
        https://mrugesh.dev/about
        https://mrugesh.dev/blog/how-to-delete-github-actions-caches-with-github-cli
        https://mrugesh.dev/blog/how-do-i-make-zsh-look-good
    secrets: inherit
