name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  packages: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/re-lint.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/re-test.yml
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/re-build.yml
    secrets: inherit
