# Usgae:
#
# Add a job like below, which will need to depend on the deploy job.
#
# comment:
#   if: ${{ github.event_name == 'pull_request' }}
#   uses: raisedadead/portfolio/.github/workflows/comment.yml@main
#   needs: [deploy]
#   with:
#     issue-number: ${{ github.event.pull_request.number }}
#     url: ${{ needs.deploy.outputs.url }}
#     alias: ${{ needs.deploy.outputs.alias }}
#     environment: ${{ needs.deploy.outputs.environment }}
#     deployment_id: ${{ needs.deploy.outputs.deployment_id }}

name: Comment

on:
  workflow_call:
    inputs:
      url:
        description: 'The URL to comment on the PR'
        required: true
        type: string
      deployment_id:
        description: 'The ID of the deployment'
        required: true
        type: string
      alias:
        description: 'The alias of the deployment'
        required: true
        type: string
      environment:
        description: 'The environment of the deployment'
        required: true
        type: string
      issue-number:
        description: 'The issue number to comment on'
        required: true
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Find Previous Comment
        uses: peter-evans/find-comment@034abe94d3191f9c89d870519735beae326f2bdb # v2
        id: fc
        with:
          issue-number: ${{ inputs.issue-number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Deployed to Cloudflare Pages'

      - name: Comment previous step output on Pull Request
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666 # v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          issue-number: ${{ inputs.issue-number }}
          body: |
            #### Deployed to Cloudflare Pages:

            **[`${{ inputs.url }}`](${{ inputs.url }})**

            <details>
            <summary>More details: </summary>

            | Step          | Status |
            | :----         | :------ |
            | Deployment Id | ${{ inputs.deployment_id }} |
            | URL Alias     | ${{ inputs.alias }} |
            | URL           | ${{ inputs.url }} |
            | Environment   | ${{ inputs.environment }} |

            </details>
