# Usgae:
#
# Add a job like below, which will need to depend on the deploy job.
#
# comment:
#   if: ${{ github.event_name == 'pull_request' }}
#   uses: raisedadead/portfolio/.github/workflows/comment.yml@main
#   needs: [deploy]
#   with:
#     issue-number: ${{ github.event.pull_request.number }}
#     url: ${{ needs.deploy.outputs.url }}
#     alias: ${{ needs.deploy.outputs.alias }}
#     environment: ${{ needs.deploy.outputs.environment }}
#     deployment_id: ${{ needs.deploy.outputs.deployment_id }}

name: Comment

on:
  workflow_call:
    inputs:
      is-pr-deploying:
        description: 'Is the PR being deployed'
        type: boolean
        default: false
      url:
        description: 'The URL to comment on the PR'
        type: string
        default: ''
      deployment_id:
        description: 'The ID of the deployment'
        type: string
        default: ''
      alias:
        description: 'The alias of the deployment'
        type: string
        default: ''
      environment:
        description: 'The environment of the deployment'
        type: string
        default: ''
      issue-number:
        description: 'The issue number to comment on'
        type: string
        default: ''

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Find Previous Comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2
        id: fc
        with:
          issue-number: ${{ inputs.issue-number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Deployment Details'

      - name: Comment previous step output on Pull Request
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b # v3
        if: ${{ inputs.is-pr-deploying == false }}}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          issue-number: ${{ inputs.issue-number }}
          body: |
            #### Deployment Details:

            **Preview Link: [`${{ inputs.url }}`](${{ inputs.url }})**

            <details>
            <summary>More details: </summary>

            | Step          | Status |
            | :----         | :------ |
            | Deployment Id | ${{ inputs.deployment_id }} |
            | URL Alias     | ${{ inputs.alias }} |
            | URL           | ${{ inputs.url }} |
            | Environment   | ${{ inputs.environment }} |

            </details>

      - name: Comment on Pull Request
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b # v3
        if: ${{ inputs.is-pr-deploying == true }}}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          issue-number: ${{ inputs.issue-number }}
          body: |
            #### Deployment Details:

            _There is a deployment in progress..._
