name: Housekeeping

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: 'WyriHaximus/github-action-wait-for-status@v2'
        with:
          ignoreActions: automerge
          checkInterval: 20
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Merge Minor SemVer Updates'
        if: steps.waitforstatuschecks.outputs.status == 'success'
        uses: ahmadnassri/action-dependabot-auto-merge@v1
        with:
          target: minor
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
      - name: 'Merge Patch SemVer Updates'
        if: steps.waitforstatuschecks.outputs.status == 'success'
        uses: ahmadnassri/action-dependabot-auto-merge@v1
        with:
          target: patch
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
