name: CI

# Continious integration enabled for all pull requests to master branch
# and pushes to all branches other than master. Direct pushes to master
# are handled in the continious delivery workflow
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and lint
        run: |
          npm ci
          npm run lint --if-present
        env:
          CI: true

  build:
    name: Build site
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Upload site artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  preview:
    name: Deploy Preview to Netlify
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Download site artifacts
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Display structure of downloaded files
        run: ls -R
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --message=Preview-${GITHUB_SHA}
      - name: Netlify Preview URL
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "
            Inspect: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}\n
            Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_URL }}
          "
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false
