name: Lighthouse CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-audit:
    name: PR Build Audit
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Find existing comment
        id: find-comment-early
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- lighthouse-audit-comment -->'

      - name: Post in-progress comment
        id: post-comment
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment-early.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Lighthouse Audit Results**

            🔄 **Running Lighthouse audits...** (3 runs per URL)

            This may take a few minutes. Results will appear here when complete.

            <!-- lighthouse-audit-comment -->

      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22.x'
          package-manager-cache: false

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Run Lighthouse (3 runs per URL)
        run: pnpm exec lhci collect --config=.github/lighthouse/lhci.json

      - name: Generate manifest with median scores
        run: node .github/scripts/lighthouse/generate-manifest.js

      - name: Download baseline artifact
        id: download-baseline
        continue-on-error: true
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: lighthouse-baseline
          path: ./

      - name: Compare scores
        run: |
          node .github/scripts/lighthouse/compare-scores.js \
            .lighthouseci/manifest.json \
            baseline-manifest.json \
            comparison.json

      - name: Format PR comment
        run: |
          node .github/scripts/lighthouse/format-report.js comparison.json comment.md

      - name: Update PR comment with results
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.post-comment.outputs.comment-id }}
          body-path: comment.md
          edit-mode: replace

      - name: Update comment on failure
        if: failure()
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.post-comment.outputs.comment-id || steps.find-comment-early.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Lighthouse Audit Results**

            **Workflow failed:** Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

            <!-- lighthouse-audit-comment -->

  production-audit:
    name: Production Audit
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22.x'
          package-manager-cache: false

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Wait for Cloudflare deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          node .github/scripts/lighthouse/wait-deployment.js ${{ github.sha }} 600

      - name: Run production Lighthouse audits (3 runs per URL)
        run: |
          pnpm exec lhci collect \
            --url="https://mrugesh.dev/" \
            --url="https://mrugesh.dev/blog" \
            --url="https://mrugesh.dev/about" \
            --url="https://mrugesh.dev/blog/how-to-delete-github-actions-caches-with-github-cli" \
            --url="https://mrugesh.dev/blog/how-do-i-make-zsh-look-good" \
            --numberOfRuns=3

      - name: Generate manifest with median scores
        run: node .github/scripts/lighthouse/generate-manifest.js

      - name: Store baseline for next run
        run: |
          cp .lighthouseci/manifest.json baseline-manifest.json

      - name: Upload baseline artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: lighthouse-baseline
          path: baseline-manifest.json
          retention-days: 1
