name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
          NPM_TOKEN_FONTAWESOME: ${{ secrets.NPM_TOKEN_FONTAWESOME }}
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@latest
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
