name: Lighthouse CI/CD

on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-audit:
    name: Lighthouse - pull request
    if: |
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '/run-lighthouse'))
    runs-on: ubuntu-latest
    concurrency:
      group: lighthouse-pr-${{ github.event.issue.number }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: ${{ github.repository }}
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Find existing comment
        id: find-comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- lighthouse-audit-comment -->'

      - name: Post in-progress comment
        id: post-comment
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Lighthouse Audit Results**

            🔄 **Running Lighthouse audits...** (3 runs per URL)

            This may take a few minutes. Results will appear here when complete.

            <!-- lighthouse-audit-comment -->

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '22.20.0'
          turbo-cache-prefix: lighthouse

      - name: Install dependencies
        run: pnpm install

      - name: Build site with Turbo
        run: pnpm exec turbo build
        env:
          CI: true
          TURBO_API: ${{ secrets.TURBO_API }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Run Lighthouse (3 runs per URL)
        run: pnpm exec lhci collect --config=.github/lighthouse/lhci.json

      - name: Generate manifest with median scores
        run: node .github/scripts/lighthouse/generate-manifest.js

      - name: Download baseline artifact
        id: download-baseline
        continue-on-error: true
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          workflow: lighthouse.yml
          name: lighthouse-baseline
          path: ./
          branch: main
          workflow_conclusion: success

      - name: Compare scores
        run: |
          node .github/scripts/lighthouse/compare-scores.js \
            .lighthouseci/manifest.json \
            baseline-manifest.json \
            comparison.json

      - name: Format PR comment
        run: |
          node .github/scripts/lighthouse/format-report.js comparison.json comment.md

      - name: Update PR comment with results
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.post-comment.outputs.comment-id }}
          body-path: comment.md
          edit-mode: replace

      - name: Update comment on failure
        if: failure()
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.post-comment.outputs.comment-id || steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Lighthouse Audit Results**

            **Workflow failed:** Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

            <!-- lighthouse-audit-comment -->

  main-audit:
    name: Lighthouse - main branch
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    concurrency:
      group: lighthouse-main-${{ github.run_id }}
      cancel-in-progress: false
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '22.20.0'
          turbo-cache-prefix: main-lighthouse

      - name: Install dependencies
        run: pnpm install

      - name: Wait for Cloudflare deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/lighthouse/wait-deployment.js ${{ github.sha }} 600

      - name: Run production Lighthouse audits (3 runs per URL)
        run: |
          pnpm exec lhci collect \
            --url="https://mrugesh.dev/" \
            --url="https://mrugesh.dev/blog" \
            --url="https://mrugesh.dev/about" \
            --url="https://mrugesh.dev/blog/how-to-delete-github-actions-caches-with-github-cli" \
            --url="https://mrugesh.dev/blog/how-do-i-make-zsh-look-good" \
            --numberOfRuns=3

      - name: Generate manifest with median scores
        run: node .github/scripts/lighthouse/generate-manifest.js

      - name: Download previous baseline
        id: download-previous-baseline
        continue-on-error: true
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          workflow: lighthouse.yml
          name: lighthouse-baseline
          path: ./
          branch: main
          workflow_conclusion: success

      - name: Compare scores
        run: |
          node .github/scripts/lighthouse/compare-scores.js \
            .lighthouseci/manifest.json \
            baseline-manifest.json \
            comparison.json

      - name: Format production summary
        run: |
          node .github/scripts/lighthouse/format-report.js comparison.json production-summary.md production

      - name: Add to workflow summary
        run: cat production-summary.md >> $GITHUB_STEP_SUMMARY

      - name: Store baseline for next run
        run: |
          cp .lighthouseci/manifest.json baseline-manifest.json

      - name: Upload baseline artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: lighthouse-baseline
          path: baseline-manifest.json
          retention-days: 7
