name: Build

on:
  workflow_call:
    inputs:
      upload-artifacts:
        description: 'Whether to upload build artifacts'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
          token: ${{ secrets.ARTICLES_PAT }}

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          turbo-cache-prefix: build

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          CI: true
          TURBO_API: ${{ secrets.TURBO_API }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Upload build artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: build-output-node-${{ matrix.node-version }}
          path: dist/
          retention-days: 1
